modal 컴포넌트 백그라운드 컴포넌트 생성
boostcamp-2020/Project16-D-Account-Book pull request #115
Opened 2020-11-24 15:25 UTC by lacomaco

## 관련 이슈
[공통 컴포넌트] 모달 컴포넌트 #87 

## 구현/수정 내용
- 자신이 포함하고 있지 않은 DOM이 클릭되어졌을때 발동하는 useClickOutside 커스텀 훅을 생성했습니다.
- 자기 자신이 클릭되어졌을때 이벤트를 발생시키는 useClickMe 커스텀훅을 생성했습니다.
- modal의 검정 백그라운드 컴포넌트를 생성했습니다.
- modal의 형태와 modal이 기능하는 예제를 담은 스토리를 생성했습니다.

@boostcamp-2020/accountbook_mentor

2020-11-24 22:35 UTC, mu1616 approved these changes
커스텀훅에 테스트코드까지.. 항상 영근님 코드보고 많이 배웁니다!!
수고 많으셨습니다!! :smile:

2020-11-24 22:35 UTC, mu1616 commented on client/src/hook/use-click-outside/useClickOutside.tsx
> +      if (ref.current && !ref.current.contains(e.target as Node)) {
e.target as Node 처음 보는 문법인데 무슨 뜻인가요..??

2020-11-24 22:35 UTC, mu1616 commented on client/src/components/modal-background/ModalBackground.stories.tsx
> +      </ModalBackground>
혹시 이 부분을 display:none으로 조작하는게 아니라 아래와 같이 show 상태에 따라 렌더링 여부를 결정해주는건 어떻게 생각하시나요??
```
{show && <ModalBackground show={show} closeModal={closeModal}>
        <div>안녕하세요</div>
      </ModalBackground>
```

2020-11-25 01:09 UTC, mu1616 commented on client/src/hook/use-click-outside/useClickOutside.tsx
> +      if (ref.current && !ref.current.contains(e.target as Node)) {
ㅎㅇ

2020-11-25 01:11 UTC, Mong-Gu approved these changes
솔직히 완전 다 이해는 못했지만 하면서 더 참고하도록 하겠습니다..! 수고하셨습니다!

2020-11-25 01:29 UTC, bbbyung2 requested changes

2020-11-25 01:29 UTC, bbbyung2 commented on client/src/components/modal-background/ModalBackground.stories.tsx
> +        1 + 1;
1 + 1 수정해주시면 좋을 것 같아요!

2020-11-25 01:56 UTC, bbbyung2 approved these changes

2020-11-25 01:56 UTC, lacomaco commented on client/src/components/modal-background/ModalBackground.stories.tsx
> +        1 + 1;
수정했습니다 🥰

2020-11-25 01:56 UTC, merged